idf_component_register(
    SRC_DIRS 
        "src"
        "src/Chain"
        "src/ChainAngle"
        "src/ChainBuzzer"
        "src/ChainCommon"
        "src/ChainDLight"
        "src/ChainENV"
        "src/ChainEncoder"
        "src/ChainIMU"
        "src/ChainJoystick"
        "src/ChainKey"
        "src/ChainMIC"
        "src/ChainMono"
        "src/ChainRGB"
        "src/ChainPIR"
        "src/ChainPedal"
        "src/ChainSwitch"
        "src/ChainToF"
        "src/Unit8Servos2Chain"
        "src/UnitChainBus"
    INCLUDE_DIRS 
        "src"
        "src/Chain"
        "src/ChainAngle"
        "src/ChainBuzzer"
        "src/ChainCommon"
        "src/ChainDLight"
        "src/ChainENV"
        "src/ChainEncoder"
        "src/ChainJoystick"
        "src/ChainKey"
        "src/ChainMIC"
        "src/ChainMono"
        "src/ChainRGB"
        "src/ChainPIR"
        "src/ChainSwitch"
        "src/ChainToF"
        "src/ChainPedal"
        "src/Unit8Servos2Chain"
        "src/UnitChainBus"
    REQUIRES 
        "driver"
        "esp_timer"
        "freertos"
)
